-- Migration script for the health-live project.
-- This script creates a table to store ingested health metrics and workouts
-- from Health Auto Export. It also adds an index on ingest_date to
-- optimize queries over date ranges.

create table if not exists public.health_metrics (
  id bigint generated by default as identity primary key,
  ingest_date timestamptz not null,
  metrics jsonb,
  workouts jsonb,
  payload jsonb,
  created_at timestamptz not null default now()
);

create index if not exists health_metrics_ingest_date_idx on public.health_metrics (ingest_date);
